ALTER TABLE test.area_alias ADD CONSTRAINT area_alias_pkey PRIMARY KEY (id);
CREATE INDEX area_alias_idx_area ON test.area_alias (area) USING btree ;
CREATE UNIQUE INDEX area_alias_idx_primary ON test.area_alias (area, locale(100)) USING btree ;
ALTER TABLE test.area_alias_type ADD CONSTRAINT area_alias_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX area_alias_type_idx_gid ON test.area_alias_type (gid) USING btree ;
ALTER TABLE test.area ADD CONSTRAINT area_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX area_idx_gid ON test.area (gid) USING btree ;
CREATE INDEX area_idx_name ON test.area (name(100)) USING btree ;
ALTER TABLE test.area_type ADD CONSTRAINT area_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX area_type_idx_gid ON test.area_type (gid) USING btree ;
ALTER TABLE test.artist_alias ADD CONSTRAINT artist_alias_pkey PRIMARY KEY (id);
CREATE INDEX artist_alias_idx_artist ON test.artist_alias (artist) USING btree ;
CREATE UNIQUE INDEX artist_alias_idx_primary ON test.artist_alias (artist, locale(100)) USING btree ;
ALTER TABLE test.artist_alias_type ADD CONSTRAINT artist_alias_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX artist_alias_type_idx_gid ON test.artist_alias_type (gid) USING btree ;
ALTER TABLE test.artist_credit_name ADD CONSTRAINT artist_credit_name_pkey PRIMARY KEY (artist_credit, position);
CREATE INDEX artist_credit_name_idx_artist ON test.artist_credit_name (artist) USING btree ;
ALTER TABLE test.artist_credit ADD CONSTRAINT artist_credit_pkey PRIMARY KEY (id);
ALTER TABLE test.artist_ipi ADD CONSTRAINT artist_ipi_pkey PRIMARY KEY (artist, ipi);
ALTER TABLE test.artist_isni ADD CONSTRAINT artist_isni_pkey PRIMARY KEY (artist, isni);
ALTER TABLE test.artist ADD CONSTRAINT artist_pkey PRIMARY KEY (id);
CREATE INDEX artist_idx_area ON test.artist (area) USING btree ;
CREATE INDEX artist_idx_begin_area ON test.artist (begin_area) USING btree ;
CREATE INDEX artist_idx_end_area ON test.artist (end_area) USING btree ;
CREATE UNIQUE INDEX artist_idx_gid ON test.artist (gid) USING btree ;
CREATE INDEX artist_idx_name ON test.artist (name(100)) USING btree ;
CREATE UNIQUE INDEX artist_idx_null_comment ON test.artist (name(100)) USING btree ;
CREATE INDEX artist_idx_sort_name ON test.artist (sort_name(100)) USING btree ;
CREATE UNIQUE INDEX artist_idx_uniq_name_comment ON test.artist (name(100), comment) USING btree ;
ALTER TABLE test.artist_type ADD CONSTRAINT artist_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX artist_type_idx_gid ON test.artist_type (gid) USING btree ;
ALTER TABLE test.cdtoc ADD CONSTRAINT cdtoc_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX cdtoc_idx_discid ON test.cdtoc (discid) USING btree ;
CREATE INDEX cdtoc_idx_freedb_id ON test.cdtoc (freedb_id) USING btree ;
ALTER TABLE test.country_area ADD CONSTRAINT country_area_pkey PRIMARY KEY (area);
ALTER TABLE test.gender ADD CONSTRAINT gender_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX gender_idx_gid ON test.gender (gid) USING btree ;
ALTER TABLE test.iso_3166_1 ADD CONSTRAINT iso_3166_1_pkey PRIMARY KEY (code);
CREATE INDEX iso_3166_1_idx_area ON test.iso_3166_1 (area) USING btree ;
ALTER TABLE test.iso_3166_2 ADD CONSTRAINT iso_3166_2_pkey PRIMARY KEY (code);
CREATE INDEX iso_3166_2_idx_area ON test.iso_3166_2 (area) USING btree ;
ALTER TABLE test.iso_3166_3 ADD CONSTRAINT iso_3166_3_pkey PRIMARY KEY (code);
CREATE INDEX iso_3166_3_idx_area ON test.iso_3166_3 (area) USING btree ;
ALTER TABLE test.isrc ADD CONSTRAINT isrc_pkey PRIMARY KEY (id);
CREATE INDEX isrc_idx_isrc ON test.isrc (isrc) USING btree ;
CREATE UNIQUE INDEX isrc_idx_isrc_recording ON test.isrc (isrc, recording) USING btree ;
CREATE INDEX isrc_idx_recording ON test.isrc (recording) USING btree ;
ALTER TABLE test.iswc ADD CONSTRAINT iswc_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX iswc_idx_iswc ON test.iswc (iswc, work) USING btree ;
CREATE INDEX iswc_idx_work ON test.iswc (work) USING btree ;
ALTER TABLE test.label_alias ADD CONSTRAINT label_alias_pkey PRIMARY KEY (id);
CREATE INDEX label_alias_idx_label ON test.label_alias (label) USING btree ;
CREATE UNIQUE INDEX label_alias_idx_primary ON test.label_alias (label, locale(100)) USING btree ;
ALTER TABLE test.label_alias_type ADD CONSTRAINT label_alias_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX label_alias_type_idx_gid ON test.label_alias_type (gid) USING btree ;
ALTER TABLE test.label_ipi ADD CONSTRAINT label_ipi_pkey PRIMARY KEY (label, ipi);
ALTER TABLE test.label_isni ADD CONSTRAINT label_isni_pkey PRIMARY KEY (label, isni);
ALTER TABLE test.label ADD CONSTRAINT label_pkey PRIMARY KEY (id);
CREATE INDEX label_idx_area ON test.label (area) USING btree ;
CREATE UNIQUE INDEX label_idx_gid ON test.label (gid) USING btree ;
CREATE INDEX label_idx_name ON test.label (name(100)) USING btree ;
CREATE UNIQUE INDEX label_idx_null_comment ON test.label (name(100)) USING btree ;
CREATE UNIQUE INDEX label_idx_uniq_name_comment ON test.label (name(100), comment) USING btree ;
ALTER TABLE test.label_type ADD CONSTRAINT label_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX label_type_idx_gid ON test.label_type (gid) USING btree ;
ALTER TABLE test.language ADD CONSTRAINT language_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX language_idx_iso_code_1 ON test.language (iso_code_1) USING btree ;
CREATE UNIQUE INDEX language_idx_iso_code_2b ON test.language (iso_code_2b) USING btree ;
CREATE UNIQUE INDEX language_idx_iso_code_2t ON test.language (iso_code_2t) USING btree ;
CREATE UNIQUE INDEX language_idx_iso_code_3 ON test.language (iso_code_3) USING btree ;
ALTER TABLE test.medium_cdtoc ADD CONSTRAINT medium_cdtoc_pkey PRIMARY KEY (id);
CREATE INDEX medium_cdtoc_idx_cdtoc ON test.medium_cdtoc (cdtoc) USING btree ;
CREATE INDEX medium_cdtoc_idx_medium ON test.medium_cdtoc (medium) USING btree ;
CREATE UNIQUE INDEX medium_cdtoc_idx_uniq ON test.medium_cdtoc (medium, cdtoc) USING btree ;
ALTER TABLE test.medium_format ADD CONSTRAINT medium_format_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX medium_format_idx_gid ON test.medium_format (gid) USING btree ;
ALTER TABLE test.medium ADD CONSTRAINT medium_pkey PRIMARY KEY (id);
ALTER TABLE test.medium ADD CONSTRAINT medium_uniq UNIQUE (test.medium.release, position) ;
CREATE INDEX medium_idx_track_count ON test.medium (track_count) USING btree ;
ALTER TABLE test.place_alias ADD CONSTRAINT place_alias_pkey PRIMARY KEY (id);
CREATE INDEX place_alias_idx_place ON test.place_alias (place) USING btree ;
CREATE UNIQUE INDEX place_alias_idx_primary ON test.place_alias (place, locale(100)) USING btree ;
ALTER TABLE test.place_alias_type ADD CONSTRAINT place_alias_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX place_alias_type_idx_gid ON test.place_alias_type (gid) USING btree ;
ALTER TABLE test.place ADD CONSTRAINT place_pkey PRIMARY KEY (id);
CREATE INDEX place_idx_area ON test.place (area) USING btree ;
CREATE UNIQUE INDEX place_idx_gid ON test.place (gid) USING btree ;
CREATE INDEX place_idx_name ON test.place (name(100)) USING btree ;
ALTER TABLE test.place_type ADD CONSTRAINT place_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX place_type_idx_gid ON test.place_type (gid) USING btree ;
ALTER TABLE test.recording ADD CONSTRAINT recording_pkey PRIMARY KEY (id);
CREATE INDEX recording_idx_artist_credit ON test.recording (artist_credit) USING btree ;
CREATE UNIQUE INDEX recording_idx_gid ON test.recording (gid) USING btree ;
CREATE INDEX recording_idx_name ON test.recording (name(100)) USING btree ;
ALTER TABLE test.release_country ADD CONSTRAINT release_country_pkey PRIMARY KEY (test.release_country.release, country);
CREATE INDEX release_country_idx_country ON test.release_country (country) USING btree ;
ALTER TABLE test.release_group_primary_type ADD CONSTRAINT release_group_primary_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX release_group_primary_type_idx_gid ON test.release_group_primary_type (gid) USING btree ;
ALTER TABLE test.release_group ADD CONSTRAINT release_group_pkey PRIMARY KEY (id);
CREATE INDEX release_group_idx_artist_credit ON test.release_group (artist_credit) USING btree ;
CREATE UNIQUE INDEX release_group_idx_gid ON test.release_group (gid) USING btree ;
CREATE INDEX release_group_idx_name ON test.release_group (name(100)) USING btree ;
ALTER TABLE test.release_group_secondary_type_join ADD CONSTRAINT release_group_secondary_type_join_pkey PRIMARY KEY (release_group, secondary_type);
ALTER TABLE test.release_group_secondary_type ADD CONSTRAINT release_group_secondary_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX release_group_secondary_type_idx_gid ON test.release_group_secondary_type (gid) USING btree ;
ALTER TABLE test.release_label ADD CONSTRAINT release_label_pkey PRIMARY KEY (id);
CREATE INDEX release_label_idx_label ON test.release_label (label) USING btree ;
CREATE INDEX release_label_idx_release ON test.release_label (test.release_label.release) USING btree ;
ALTER TABLE test.release_packaging ADD CONSTRAINT release_packaging_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX release_packaging_idx_gid ON test.release_packaging (gid) USING btree ;
ALTER TABLE test.release ADD CONSTRAINT release_pkey PRIMARY KEY (id);
CREATE INDEX release_idx_artist_credit ON test.release (artist_credit) USING btree ;
CREATE UNIQUE INDEX release_idx_gid ON test.release (gid) USING btree ;
CREATE INDEX release_idx_name ON test.release (name(100)) USING btree ;
CREATE INDEX release_idx_release_group ON test.release (release_group) USING btree ;
ALTER TABLE test.release_status ADD CONSTRAINT release_status_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX release_status_idx_gid ON test.release_status (gid) USING btree ;
ALTER TABLE test.release_unknown_country ADD CONSTRAINT release_unknown_country_pkey PRIMARY KEY (test.release_unknown_country.release);
ALTER TABLE test.script ADD CONSTRAINT script_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX script_idx_iso_code ON test.script (iso_code) USING btree ;
ALTER TABLE test.track ADD CONSTRAINT track_pkey PRIMARY KEY (id);
ALTER TABLE test.track ADD CONSTRAINT track_uniq_medium_position UNIQUE (medium, position) ;
CREATE INDEX track_idx_artist_credit ON test.track (artist_credit) USING btree ;
CREATE UNIQUE INDEX track_idx_gid ON test.track (gid) USING btree ;
CREATE INDEX track_idx_recording ON test.track (recording) USING btree ;
ALTER TABLE test.work_alias ADD CONSTRAINT work_alias_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX work_alias_idx_primary ON test.work_alias (work, locale(100)) USING btree ;
CREATE INDEX work_alias_idx_work ON test.work_alias (work) USING btree ;
ALTER TABLE test.work_alias_type ADD CONSTRAINT work_alias_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX work_alias_type_idx_gid ON test.work_alias_type (gid) USING btree ;
ALTER TABLE test.work_attribute ADD CONSTRAINT work_attribute_pkey PRIMARY KEY (id);
CREATE INDEX work_attribute_idx_work ON test.work_attribute (work) USING btree ;
ALTER TABLE test.work_attribute_type_allowed_value ADD CONSTRAINT work_attribute_type_allowed_value_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX work_attribute_type_allowed_value_idx_gid ON test.work_attribute_type_allowed_value (gid) USING btree ;
CREATE INDEX work_attribute_type_allowed_value_idx_name ON test.work_attribute_type_allowed_value (work_attribute_type) USING btree ;
ALTER TABLE test.work_attribute_type ADD CONSTRAINT work_attribute_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX work_attribute_type_idx_gid ON test.work_attribute_type (gid) USING btree ;
ALTER TABLE test.work_language ADD CONSTRAINT work_language_pkey PRIMARY KEY (work, language);
ALTER TABLE test.work ADD CONSTRAINT work_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX work_idx_gid ON test.work (gid) USING btree ;
CREATE INDEX work_idx_name ON test.work (name(100)) USING btree ;
ALTER TABLE test.work_type ADD CONSTRAINT work_type_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX work_type_idx_gid ON test.work_type (gid) USING btree ;
ALTER TABLE test.area_alias ADD CONSTRAINT area_alias_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.area_alias ADD CONSTRAINT area_alias_fk_type FOREIGN KEY (type) REFERENCES test.area_alias_type(id);
ALTER TABLE test.area_alias_type ADD CONSTRAINT area_alias_type_fk_parent FOREIGN KEY (parent) REFERENCES test.area_alias_type(id);
ALTER TABLE test.area ADD CONSTRAINT area_fk_type FOREIGN KEY (type) REFERENCES test.area_type(id);
ALTER TABLE test.area_type ADD CONSTRAINT area_type_fk_parent FOREIGN KEY (parent) REFERENCES test.area_type(id);
ALTER TABLE test.artist_alias ADD CONSTRAINT artist_alias_fk_artist FOREIGN KEY (artist) REFERENCES test.artist(id);
ALTER TABLE test.artist_alias ADD CONSTRAINT artist_alias_fk_type FOREIGN KEY (type) REFERENCES test.artist_alias_type(id);
ALTER TABLE test.artist_alias_type ADD CONSTRAINT artist_alias_type_fk_parent FOREIGN KEY (parent) REFERENCES test.artist_alias_type(id);
ALTER TABLE test.artist_credit_name ADD CONSTRAINT artist_credit_name_fk_artist FOREIGN KEY (artist) REFERENCES test.artist(id) ON DELETE CASCADE;
ALTER TABLE test.artist_credit_name ADD CONSTRAINT artist_credit_name_fk_artist_credit FOREIGN KEY (artist_credit) REFERENCES test.artist_credit(id) ON DELETE CASCADE;
ALTER TABLE test.artist_ipi ADD CONSTRAINT artist_ipi_fk_artist FOREIGN KEY (artist) REFERENCES test.artist(id);
ALTER TABLE test.artist_isni ADD CONSTRAINT artist_isni_fk_artist FOREIGN KEY (artist) REFERENCES test.artist(id);
ALTER TABLE test.artist ADD CONSTRAINT artist_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.artist ADD CONSTRAINT artist_fk_begin_area FOREIGN KEY (begin_area) REFERENCES test.area(id);
ALTER TABLE test.artist ADD CONSTRAINT artist_fk_end_area FOREIGN KEY (end_area) REFERENCES test.area(id);
ALTER TABLE test.artist ADD CONSTRAINT artist_fk_gender FOREIGN KEY (gender) REFERENCES test.gender(id);
ALTER TABLE test.artist ADD CONSTRAINT artist_fk_type FOREIGN KEY (type) REFERENCES test.artist_type(id);
ALTER TABLE test.artist_type ADD CONSTRAINT artist_type_fk_parent FOREIGN KEY (parent) REFERENCES test.artist_type(id);
ALTER TABLE test.country_area ADD CONSTRAINT country_area_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.gender ADD CONSTRAINT gender_fk_parent FOREIGN KEY (parent) REFERENCES test.gender(id);
ALTER TABLE test.iso_3166_1 ADD CONSTRAINT iso_3166_1_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.iso_3166_2 ADD CONSTRAINT iso_3166_2_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.iso_3166_3 ADD CONSTRAINT iso_3166_3_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.isrc ADD CONSTRAINT isrc_fk_recording FOREIGN KEY (recording) REFERENCES test.recording(id);
ALTER TABLE test.iswc ADD CONSTRAINT iswc_fk_work FOREIGN KEY (work) REFERENCES test.work(id);
ALTER TABLE test.label_alias ADD CONSTRAINT label_alias_fk_label FOREIGN KEY (label) REFERENCES test.label(id);
ALTER TABLE test.label_alias ADD CONSTRAINT label_alias_fk_type FOREIGN KEY (type) REFERENCES test.label_alias_type(id);
ALTER TABLE test.label_alias_type ADD CONSTRAINT label_alias_type_fk_parent FOREIGN KEY (parent) REFERENCES test.label_alias_type(id);
ALTER TABLE test.label_ipi ADD CONSTRAINT label_ipi_fk_label FOREIGN KEY (label) REFERENCES test.label(id);
ALTER TABLE test.label_isni ADD CONSTRAINT label_isni_fk_label FOREIGN KEY (label) REFERENCES test.label(id);
ALTER TABLE test.label ADD CONSTRAINT label_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.label ADD CONSTRAINT label_fk_type FOREIGN KEY (type) REFERENCES test.label_type(id);
ALTER TABLE test.label_type ADD CONSTRAINT label_type_fk_parent FOREIGN KEY (parent) REFERENCES test.label_type(id);
ALTER TABLE test.medium_cdtoc ADD CONSTRAINT medium_cdtoc_fk_cdtoc FOREIGN KEY (cdtoc) REFERENCES test.cdtoc(id);
ALTER TABLE test.medium_cdtoc ADD CONSTRAINT medium_cdtoc_fk_medium FOREIGN KEY (medium) REFERENCES test.medium(id);
ALTER TABLE test.medium_format ADD CONSTRAINT medium_format_fk_parent FOREIGN KEY (parent) REFERENCES test.medium_format(id);
ALTER TABLE test.medium ADD CONSTRAINT medium_fk_format FOREIGN KEY (format) REFERENCES test.medium_format(id);
ALTER TABLE test.medium ADD CONSTRAINT medium_fk_release FOREIGN KEY (test.medium.release) REFERENCES test.release(id);
ALTER TABLE test.place_alias ADD CONSTRAINT place_alias_fk_place FOREIGN KEY (place) REFERENCES test.place(id);
ALTER TABLE test.place_alias ADD CONSTRAINT place_alias_fk_type FOREIGN KEY (type) REFERENCES test.place_alias_type(id);
ALTER TABLE test.place_alias_type ADD CONSTRAINT place_alias_type_fk_parent FOREIGN KEY (parent) REFERENCES test.place_alias_type(id);
ALTER TABLE test.place ADD CONSTRAINT place_fk_area FOREIGN KEY (area) REFERENCES test.area(id);
ALTER TABLE test.place ADD CONSTRAINT place_fk_type FOREIGN KEY (type) REFERENCES test.place_type(id);
ALTER TABLE test.place_type ADD CONSTRAINT place_type_fk_parent FOREIGN KEY (parent) REFERENCES test.place_type(id);
ALTER TABLE test.recording ADD CONSTRAINT recording_fk_artist_credit FOREIGN KEY (artist_credit) REFERENCES test.artist_credit(id);
ALTER TABLE test.release_country ADD CONSTRAINT release_country_fk_country FOREIGN KEY (country) REFERENCES test.country_area(area);
ALTER TABLE test.release_country ADD CONSTRAINT release_country_fk_release FOREIGN KEY (test.release_country.release) REFERENCES test.release(id);
ALTER TABLE test.release_group_primary_type ADD CONSTRAINT release_group_primary_type_fk_parent FOREIGN KEY (parent) REFERENCES test.release_group_primary_type(id);
ALTER TABLE test.release_group ADD CONSTRAINT release_group_fk_artist_credit FOREIGN KEY (artist_credit) REFERENCES test.artist_credit(id);
ALTER TABLE test.release_group ADD CONSTRAINT release_group_fk_type FOREIGN KEY (type) REFERENCES test.release_group_primary_type(id);
ALTER TABLE test.release_group_secondary_type_join ADD CONSTRAINT release_group_secondary_type_join_fk_release_group FOREIGN KEY (release_group) REFERENCES test.release_group(id);
ALTER TABLE test.release_group_secondary_type_join ADD CONSTRAINT release_group_secondary_type_join_fk_secondary_type FOREIGN KEY (secondary_type) REFERENCES test.release_group_secondary_type(id);
ALTER TABLE test.release_group_secondary_type ADD CONSTRAINT release_group_secondary_type_fk_parent FOREIGN KEY (parent) REFERENCES test.release_group_secondary_type(id);
ALTER TABLE test.release_label ADD CONSTRAINT release_label_fk_label FOREIGN KEY (label) REFERENCES test.label(id);
ALTER TABLE test.release_label ADD CONSTRAINT release_label_fk_release FOREIGN KEY (test.release_label.release) REFERENCES test.release(id);
ALTER TABLE test.release_packaging ADD CONSTRAINT release_packaging_fk_parent FOREIGN KEY (parent) REFERENCES test.release_packaging(id);
ALTER TABLE test.release ADD CONSTRAINT release_fk_artist_credit FOREIGN KEY (artist_credit) REFERENCES test.artist_credit(id);
ALTER TABLE test.release ADD CONSTRAINT release_fk_language FOREIGN KEY (language) REFERENCES test.language(id);
ALTER TABLE test.release ADD CONSTRAINT release_fk_packaging FOREIGN KEY (packaging) REFERENCES test.release_packaging(id);
ALTER TABLE test.release ADD CONSTRAINT release_fk_release_group FOREIGN KEY (release_group) REFERENCES test.release_group(id);
ALTER TABLE test.release ADD CONSTRAINT release_fk_script FOREIGN KEY (script) REFERENCES test.script(id);
ALTER TABLE test.release ADD CONSTRAINT release_fk_status FOREIGN KEY (status) REFERENCES test.release_status(id);
ALTER TABLE test.release_status ADD CONSTRAINT release_status_fk_parent FOREIGN KEY (parent) REFERENCES test.release_status(id);
ALTER TABLE test.release_unknown_country ADD CONSTRAINT release_unknown_country_fk_release FOREIGN KEY (test.release_unknown_country.release) REFERENCES test.release(id);
ALTER TABLE test.track ADD CONSTRAINT track_fk_artist_credit FOREIGN KEY (artist_credit) REFERENCES test.artist_credit(id);
ALTER TABLE test.track ADD CONSTRAINT track_fk_medium FOREIGN KEY (medium) REFERENCES test.medium(id);
ALTER TABLE test.track ADD CONSTRAINT track_fk_recording FOREIGN KEY (recording) REFERENCES test.recording(id);
ALTER TABLE test.work_alias ADD CONSTRAINT work_alias_fk_type FOREIGN KEY (type) REFERENCES test.work_alias_type(id);
ALTER TABLE test.work_alias ADD CONSTRAINT work_alias_fk_work FOREIGN KEY (work) REFERENCES test.work(id);
ALTER TABLE test.work_alias_type ADD CONSTRAINT work_alias_type_fk_parent FOREIGN KEY (parent) REFERENCES test.work_alias_type(id);
ALTER TABLE test.work_attribute ADD CONSTRAINT work_attribute_fk_work FOREIGN KEY (work) REFERENCES test.work(id);
ALTER TABLE test.work_attribute ADD CONSTRAINT work_attribute_fk_work_attribute_type FOREIGN KEY (work_attribute_type) REFERENCES test.work_attribute_type(id);
ALTER TABLE test.work_attribute ADD CONSTRAINT work_attribute_fk_work_attribute_type_allowed_value FOREIGN KEY (work_attribute_type_allowed_value) REFERENCES test.work_attribute_type_allowed_value(id);
ALTER TABLE test.work_attribute_type_allowed_value ADD CONSTRAINT work_attribute_type_allowed_value_fk_parent FOREIGN KEY (parent) REFERENCES test.work_attribute_type_allowed_value(id);
ALTER TABLE test.work_attribute_type_allowed_value ADD CONSTRAINT work_attribute_type_allowed_value_fk_work_attribute_type FOREIGN KEY (work_attribute_type) REFERENCES test.work_attribute_type(id);
ALTER TABLE test.work_attribute_type ADD CONSTRAINT work_attribute_type_fk_parent FOREIGN KEY (parent) REFERENCES test.work_attribute_type(id);
ALTER TABLE test.work_language ADD CONSTRAINT work_language_fk_language FOREIGN KEY (language) REFERENCES test.language(id);
ALTER TABLE test.work_language ADD CONSTRAINT work_language_fk_work FOREIGN KEY (work) REFERENCES test.work(id);
ALTER TABLE test.work ADD CONSTRAINT work_fk_type FOREIGN KEY (type) REFERENCES test.work_type(id);
ALTER TABLE test.work_type ADD CONSTRAINT work_type_fk_parent FOREIGN KEY (parent) REFERENCES test.work_type(id);
