files = ['alternative_release_type', 'annotation', 'area', 'area_alias', 'area_alias_type', 'area_annotation',
         'area_gid_redirect', 'area_tag', 'area_tag_raw', 'area_type', 'artist', 'artist_alias', 'artist_alias_type',
         'artist_annotation', 'artist_credit', 'artist_credit_name', 'artist_gid_redirect', 'artist_ipi', 'artist_isni',
         'artist_meta', 'artist_rating_raw', 'artist_tag', 'artist_tag_raw', 'artist_type', 'cdtoc', 'country_area',
         'cover_art', 'cover_art_archive.art_type', 'cover_art_archive.image_type', 'edit', 'editor',
         'editor_collection', 'editor_collection_area', 'editor_collection_artist', 'editor_collection_event',
         'editor_collection_label', 'editor_collection_recording', 'editor_collection_release',
         'editor_collection_release_group', 'editor_collection_type', 'editor_collection_work', 'editor_language',
         'editor_subscribe_artist', 'editor_subscribe_label', 'editor_subscribe_series', 'edit_artist', 'edit_data',
         'edit_recording', 'edit_release', 'edit_release_group', 'edit_work', 'event', 'event_alias',
         'event_alias_type', 'event_annotation', 'event_gid_redirect', 'event_meta', 'event_rating_raw', 'event_tag',
         'event_tag_raw', 'event_type', 'gender', 'genre', 'genre_alias', 'genre_alias_type', 'instrument',
         'instrument_alias', 'instrument_alias_type', 'instrument_annotation', 'instrument_tag', 'instrument_tag_raw',
         'instrument_type', 'iso_3166_1', 'iso_3166_2', 'iso_3166_3', 'isrc', 'iswc', 'label', 'label_alias',
         'label_alias_type', 'label_annotation', 'label_gid_redirect', 'label_ipi', 'label_isni', 'label_meta',
         'label_rating_raw', 'label_tag', 'label_tag_raw', 'label_type', 'language', 'link', 'link_attribute',
         'link_attribute_credit', 'link_attribute_text_value', 'link_attribute_type', 'link_creditable_attribute_type',
         'link_text_attribute_type', 'link_type', 'link_type_attribute_type', 'l_area_area', 'l_area_event',
         'l_area_genre', 'l_area_instrument', 'l_area_recording', 'l_area_release', 'l_area_series', 'l_area_url',
         'l_area_work', 'l_artist_artist', 'l_artist_event', 'l_artist_label', 'l_artist_place', 'l_artist_recording',
         'l_artist_release', 'l_artist_release_group', 'l_artist_series', 'l_artist_url', 'l_artist_work',
         'l_event_event', 'l_event_place', 'l_event_recording', 'l_event_release', 'l_event_release_group',
         'l_event_series', 'l_event_url', 'l_event_work', 'l_label_label', 'l_label_place', 'l_label_recording',
         'l_label_release', 'l_label_series', 'l_label_url', 'l_label_work', 'l_place_place', 'l_place_recording',
         'l_place_release', 'l_place_series', 'l_place_url', 'l_place_work', 'l_recording_recording',
         'l_recording_release', 'l_recording_series', 'l_recording_url', 'l_recording_work',
         'l_release_group_release_group', 'l_release_group_series', 'l_release_group_url', 'l_release_release',
         'l_release_series', 'l_release_url', 'l_series_series', 'l_series_url', 'l_series_work', 'l_url_work',
         'l_work_work', 'medium', 'medium_cdtoc', 'medium_format', 'medium_index', 'orderable_link_type', 'place',
         'place_alias', 'place_alias_type', 'place_annotation', 'place_gid_redirect', 'place_rating_raw', 'place_tag',
         'place_tag_raw', 'place_type', 'recording', 'recording_alias', 'recording_alias_type', 'recording_annotation',
         'recording_gid_redirect', 'recording_meta', 'recording_rating_raw', 'recording_tag', 'recording_tag_raw',
         'release', 'release_alias', 'release_alias_type', 'release_annotation', 'release_country',
         'release_gid_redirect', 'release_group', 'release_group_alias', 'release_group_alias_type',
         'release_group_annotation', 'release_group_gid_redirect', 'release_group_meta', 'release_group_primary_type',
         'release_group_rating_raw', 'release_group_secondary_type', 'release_group_secondary_type_join',
         'release_group_tag', 'release_group_tag_raw', 'release_label', 'release_meta', 'release_packaging',
         'release_status', 'release_tag', 'release_tag_raw', 'release_unknown_country', 'script', 'series',
         'series_alias', 'series_alias_type', 'series_annotation', 'series_gid_redirect', 'series_ordering_type',
         'series_tag', 'series_tag_raw', 'series_type', 'tag', 'track', 'url', 'url_gid_redirect', 'vote', 'work',
         'work_alias', 'work_alias_type', 'work_annotation', 'work_attribute', 'work_attribute_type',
         'work_attribute_type_allowed_value', 'work_gid_redirect', 'work_language', 'work_meta', 'work_rating_raw',
         'work_tag', 'work_tag_raw', 'work_type']

tables = ['alternative_release_type', 'annotation', 'area', 'area_alias', 'area_alias_type', 'area_annotation',
          'area_gid_redirect', 'area_tag', 'area_tag_raw', 'area_type', 'artist', 'artist_alias', 'artist_alias_type',
          'artist_annotation', 'artist_credit', 'artist_credit_name', 'artist_gid_redirect', 'artist_ipi',
          'artist_isni', 'artist_meta', 'artist_rating_raw', 'artist_tag', 'artist_tag_raw', 'artist_type', 'cdtoc',
          'country_area', 'cover_art', 'art_type', 'image_type', 'edit', 'editor', 'editor_collection',
          'editor_collection_area', 'editor_collection_artist', 'editor_collection_event', 'editor_collection_label',
          'editor_collection_recording', 'editor_collection_release', 'editor_collection_release_group',
          'editor_collection_type', 'editor_collection_work', 'editor_language', 'editor_subscribe_artist',
          'editor_subscribe_label', 'editor_subscribe_series', 'edit_artist', 'edit_data', 'edit_recording',
          'edit_release', 'edit_release_group', 'edit_work', 'event', 'event_alias', 'event_alias_type',
          'event_annotation', 'event_gid_redirect', 'event_meta', 'event_rating_raw', 'event_tag', 'event_tag_raw',
          'event_type', 'gender', 'genre', 'genre_alias', 'genre_alias_type', 'instrument', 'instrument_alias',
          'instrument_alias_type', 'instrument_annotation', 'instrument_tag', 'instrument_tag_raw', 'instrument_type',
          'iso_3166_1', 'iso_3166_2', 'iso_3166_3', 'isrc', 'iswc', 'label', 'label_alias', 'label_alias_type',
          'label_annotation', 'label_gid_redirect', 'label_ipi', 'label_isni', 'label_meta', 'label_rating_raw',
          'label_tag', 'label_tag_raw', 'label_type', 'language', 'link', 'link_attribute', 'link_attribute_credit',
          'link_attribute_text_value', 'link_attribute_type', 'link_creditable_attribute_type',
          'link_text_attribute_type', 'link_type', 'link_type_attribute_type', 'l_area_area', 'l_area_event',
          'l_area_genre', 'l_area_instrument', 'l_area_recording', 'l_area_release', 'l_area_series', 'l_area_url',
          'l_area_work', 'l_artist_artist', 'l_artist_event', 'l_artist_label', 'l_artist_place', 'l_artist_recording',
          'l_artist_release', 'l_artist_release_group', 'l_artist_series', 'l_artist_url', 'l_artist_work',
          'l_event_event', 'l_event_place', 'l_event_recording', 'l_event_release', 'l_event_release_group',
          'l_event_series', 'l_event_url', 'l_event_work', 'l_label_label', 'l_label_place', 'l_label_recording',
          'l_label_release', 'l_label_series', 'l_label_url', 'l_label_work', 'l_place_place', 'l_place_recording',
          'l_place_release', 'l_place_series', 'l_place_url', 'l_place_work', 'l_recording_recording',
          'l_recording_release', 'l_recording_series', 'l_recording_url', 'l_recording_work',
          'l_release_group_release_group', 'l_release_group_series', 'l_release_group_url', 'l_release_release',
          'l_release_series', 'l_release_url', 'l_series_series', 'l_series_url', 'l_series_work', 'l_url_work',
          'l_work_work', 'medium', 'medium_cdtoc', 'medium_format', 'medium_index', 'orderable_link_type', 'place',
          'place_alias', 'place_alias_type', 'place_annotation', 'place_gid_redirect', 'place_rating_raw', 'place_tag',
          'place_tag_raw', 'place_type', 'recording', 'recording_alias', 'recording_alias_type', 'recording_annotation',
          'recording_gid_redirect', 'recording_meta', 'recording_rating_raw', 'recording_tag', 'recording_tag_raw',
          'release', 'release_alias', 'release_alias_type', 'release_annotation', 'release_country',
          'release_gid_redirect', 'release_group', 'release_group_alias', 'release_group_alias_type',
          'release_group_annotation', 'release_group_gid_redirect', 'release_group_meta', 'release_group_primary_type',
          'release_group_rating_raw', 'release_group_secondary_type', 'release_group_secondary_type_join',
          'release_group_tag', 'release_group_tag_raw', 'release_label', 'release_meta', 'release_packaging',
          'release_status', 'release_tag', 'release_tag_raw', 'release_unknown_country', 'script', 'series',
          'series_alias', 'series_alias_type', 'series_annotation', 'series_gid_redirect', 'series_ordering_type',
          'series_tag', 'series_tag_raw', 'series_type', 'tag', 'track', 'url', 'url_gid_redirect', 'vote', 'work',
          'work_alias', 'work_alias_type', 'work_annotation', 'work_attribute', 'work_attribute_type',
          'work_attribute_type_allowed_value', 'work_gid_redirect', 'work_language', 'work_meta', 'work_rating_raw',
          'work_tag', 'work_tag_raw', 'work_type']

data_location = "/home/ubuntu/Downloads/"

for i in range(len(tables)):
    print("LOAD DATA LOCAL INFILE '" + data_location + files[i] + "' INTO TABLE test." + tables[
        i] + " FIELDS TERMINATED BY '\\t'  ESCAPED BY '\\\\'  LINES TERMINATED BY '\\n';")
